version: '{branch}-{build}'
configuration: Debug 
platform: Any CPU
image: Visual Studio 2017
environment:
  my_secret:
    secure: TQ6UX7StbAoySBfSbBAu+B0XnNUQ7I9Tsb/2Wy7XPOc=
  my_gcp_secret:
    secure: zkVb0HH9YV7arn4DrfEoiYSywjIyzpjT0n7OJaN/n5Y=
  my_gcp_salt:
    secure: STXopp4a0aI3JjAyA4S1V7Z1UDkfnXk2hZkqADE2CDbPvo2YvTtF/Jjjqzd7GQN9s72TvfG6d8Fdc78GdLldsQ==
  wss_secret:
    secure: iZbbx7JscluHEEpME5IXyMMRPSof6eXy9E0Ujndw7lcKFVlJayf0hrPaaATBt/iELDYCz8sASYpwOvjkIr+vJCeVYY1saCXkh9fdiSp5Txk=

  matrix:
    - test_framework: netcoreapp2.0
      snowflake_cloud_env: AWS
    - test_framework: net46
      snowflake_cloud_env: AWS
    - test_framework: netcoreapp2.0
      snowflake_cloud_env: AZURE
    - test_framework: net46
      snowflake_cloud_env: AZURE
    - test_framework: netcoreapp2.0
      snowflake_cloud_env: GCP
    - test_framework: net46
      snowflake_cloud_env: GCP
 
install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt Snowflake.Data.Tests\parameters.json.enc -secret %my_secret%
  - cmd: appveyor-tools\secure-file -decrypt Snowflake.Data.Tests\parameters_gcp.json.enc -secret %my_gcp_secret% -salt %my_gcp_salt%
  
before_build:
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build snowflake-connector-net.sln /p:DebugType=Full
  
before_test:
  - cmd: nuget install OpenCover -Version 4.6.519
      
test_script:
  - cmd: cd Snowflake.Data.Tests
  # test against .net core 2.0 
  - cmd: ..\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"dotnet.exe" -returntargetcode -targetargs:"test -f %test_framework% -v n" -register:user -filter:"+[Snowflake.Data]*" -output:"%test_framework%_coverage.xml" -oldStyle
  # set whitesource api key
  - cmd: export WHITESOURCE_API_KEY=%wss_secret%
  # perform whitesource scan
  - cmd: chmod 755 wss.sh
  - cmd: ./wss.sh

after_test:
 - cd ..
 - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
 - pip install codecov
 - codecov -f Snowflake.Data.Tests\%test_framework%_coverage.xml -t ffc6a21d-8176-4849-9047-e3a631dcd35a

artifacts:
  - path: 'Snowflake.Data.Tests\bin\${platform}\${configuration}\*\*.log'  
  - path: 'Snowflake.Data.Tests\*_coverage.xml'
